### ISSUE TITLE
Can this plug-in be used in maya2022?

### ISSUE THREAD

**Issue by xdiver** [kidintwo3/cc-maya-primgen#1]
An attempt was made to install it in maya2022. There is a plug-in for primgen.mll in plug-in manager, but prompt 
Error: file: D:/Maya/Maya--/Maya2022/scripts/others/pluginWin.mel line 316:

**Comment by kidintwo3** [comment]
Did you compile it for 2022?

**Comment by xdiver** [comment]
> Did you compile it for 2022?

I just copied the primgen.mll file from the 2020 version to Maya2022, which obviously didn't fail to launch the script.
This approach works in other script plug-ins.

Excuse me, can you add a file of Maya2022 version primgen. MLL

**Comment by kidintwo3** [comment]
Is open source, you can compile for any version of maya

**Comment by kidintwo3** [comment]
In the make folder there are example files and batch scripts for building the plugin. You can modify those to compile for 2022 for example.
